type Query {
  planets: [Planet!]!
  planet(planetId: ID!): Planet
}

type Mutation {
  addResourceToPlanet(planetId: ID!, input: AddResourceInput!): Boolean!
}

type Planet {
  id: ID!
  name: String!
  resources: [Resource]!
  owner: Player
}

type Resource {
  type: String!
  amount: Int!
}

input AddResourceInput {
  type: String!
  amount: Int!
}
